@group(0) @binding(0) var<storage, read> scene: Scene;
@group(0) @binding(1) var<storage, read> rays: RayBuffer;
@group(0) @binding(2) var<storage, read> bvh_buffer: BVHBuffer;
@group(0) @binding(3) var<storage, read> material_buffer: MaterialBuffer;
@group(0) @binding(4) var<storage, read> triangle_buffer: TriangleBuffer;
@group(0) @binding(5) var<storage, read> vertex_buffer: VertexBuffer;
@group(0) @binding(6) var<storage, read> normal_buffer: NormalBuffer;
@group(0) @binding(7) var<storage, read> quad_light_buffer: QuadLightBuffer;
@group(0) @binding(8) var t_sky: texture_2d<f32>;
@group(0) @binding(9) var s_sky: sampler;